---
id: 236893
name: BigQuery -> BigQuery
description: ''
user:
  id: 7286
  email: toru.nagaoka@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: bigquery
    bigquery_connection:
      id: 761
      name: csdemo-BigQuery
    gcs_uri: gs://nagaoka_test/BigQuerytest/*
    gcs_uri_format: custom_path
    query: |-
      SELECT
      *
      FROM
      `systemn-playground.nagaoka_test.demo`
    location: asia-northeast1
    temp_dataset: nagaoka_test
    cleanup_gcs_files: true
    use_legacy_sql: false
    cache: true
    file_format: CSV
    bigquery_job_wait_second: 600
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: id
        type: long
      - name: name
        type: string
      - name: mail
        type: string
      - name: prefecture
        type: long
      quote: "\""
      escape: "\""
    decoders:
    - type: gzip
  out:
    type: bigquery
    bigquery_connection:
      id: 761
      name: csdemo-BigQuery
    dataset: nagaoka_test
    table: BigQuerytest
    auto_create_dataset: false
    mode: replace
    location: asia-northeast1
    open_timeout_sec: 300
    timeout_sec: 300
    send_timeout_sec: 300
    read_timeout_sec: 300
    retries: 5
    allow_quoted_newlines: true
    column_options: []
    template_table: ''
    time_partitioning:
      type: 
      field: 
      expiration_ms: 
    custom_variables:
    - type: timestamp_runtime
      name: "$date$"
      quantity: 0
      unit: date
      direction: ago
      time_zone: Asia/Tokyo
      format: "%Y%m%d"
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: name
      src: name
      default: ''
      type: string
    - name: mail
      src: mail
      default: ''
      type: string
    - name: prefecture
      src: prefecture
      default: ''
      type: long
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
