---
id: 238915
name: MySQL -> snowflake
description: ''
user:
  id: 7286
  email: toru.nagaoka@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: mysql
    mysql_connection:
      id: 281
      name: csdemo-CloudMySQL
    database: test
    query: |-
      SELECT
      id,
      name,
      flg,
      CAST(salary AS CHAR) AS salary,
      memo
      FROM nagaoka_test
    default_timezone: ''
    fetch_rows: 10000
    connect_timeout: 300
    socket_timeout: 1800
    use_legacy_datetime_code: false
    custom_variables: []
    incremental_loading_enabled: false
  out:
    type: snowflake
    snowflake_connection:
      id: 47
      name: csdemo-Snowflake
    warehouse: TEST_WH
    database: TEST_NAGAOKA
    schema: PUBLIC
    table: TEST_MYSQL
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: replace
    default_timezone: UTC
    column_options:
      memo:
        type: VARCHAR
    empty_field_as_null: true
    batch_size: 50
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: name
      src: name
      default: ''
      type: string
    - name: flg
      src: flg
      default: ''
      type: long
    - name: salary
      src: salary
      default: ''
      type: string
    - name: memo
      src: memo
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
