---
id: 241485
name: mysql_nagaoka_test_nagaoka_test
description: ''
user:
  id: 7286
  email: toru.nagaoka@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: mysql
    mysql_connection:
      id: 281
      name: csdemo-CloudMySQL
    database: test
    query: |-
      SELECT
      id,
      name,
      flg,
      CAST(salary AS CHAR) as salary
      FROM `nagaoka_test`

      -- SELECT * FROM `nagaoka_test`
    default_timezone: Asia/Tokyo
    fetch_rows: 10000
    connect_timeout: 300
    socket_timeout: 1800
    use_legacy_datetime_code: false
    custom_variables: []
    incremental_loading_enabled: false
  out:
    type: bigquery
    bigquery_connection:
      id: 761
      name: csdemo-BigQuery
    dataset: nagaoka_test
    table: nagaoka_test
    auto_create_dataset: false
    mode: replace
    location: asia-northeast1
    open_timeout_sec: 300
    timeout_sec: 300
    send_timeout_sec: 300
    read_timeout_sec: 300
    retries: 5
    allow_quoted_newlines: true
    column_options:
    - name: salary
      type: FLOAT
      mode: NULLABLE
      description: ''
    template_table: ''
    time_partitioning:
      type: 
      field: 
      expiration_ms: 
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: name
      src: name
      default: ''
      type: string
    - name: flg
      src: flg
      default: ''
      type: long
    - name: salary
      src: salary
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
labels:
- name: nagaoka
  id: 3751
job_schedules: []
triggers: []
notifications: []
