---
id: 225917
name: すぷし -> gcs
description: ''
user:
  id: 7286
  email: toru.nagaoka@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: google_spreadsheets
    google_spreadsheets_connection:
      id: 1290
      name: MyGoogle
    spreadsheets_url: https://docs.google.com/spreadsheets/d/1jw8bRQzC4S8bYCdm9elVcyOcBaz1GQJ46D-jlrTL790/edit?usp=drive_link
    worksheet_title: シート1
    start_row: 2
    start_column: A
    default_timezone: Asia/Tokyo
    null_string: ''
    columns:
    - name: 'id '
      type: string
    - name: name
      type: string
    custom_variables: []
  out:
    type: gcs
    gcs_connection:
      id: 183
      name: csdemo-GoogleCloudStroage
    bucket: nagaoka_test
    path_prefix: test
    file_ext: ".csv"
    suppress_output_files: false
    sequence_format: ".%03d.%02d"
    custom_variables: []
    formatter:
      type: csv
      delimiter: ","
      newline: CRLF
      newline_in_field: LF
      charset: UTF-8
      quote_policy: NONE
      quote: "\""
      escape: "\\"
      header_line: true
      default_timezone: UTC
    encoders: 
  data_settings:
    columns:
    - name: 'id '
      src: 'id '
      default: ''
      type: string
    - name: name
      src: name
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
